# This powershell script watches an Obsidian vault, specifically the Daily Notes folder, for a new daily note file. When it detects a new file, it augments it with information about my meetings for the day. That information comes from copilot and is deposited in my downloads folder. The process is as follows:

# 1. The script watches the folder `C:\Users\jmutchek\OneDrive - Microsoft\10-self\12-journal\12.10-journal\journal` for new files (including watching subfolders).
# 2. When a new file is detected, it checks the `C:\Users\jmutchek\Downloads\` folder for a file that matches the name template `yyyymmdd-meetings.tar`
# 2a. If the file does not exist, it exits. This scipt can be run manually to check for this file in the downloads folder and resume processing.
# 2b. If the file exists, it extracts the contents of the tar file to a temporary folder.
# 3. The contents of the markdown file named `yyyymmdd_meetings.md` are inserted into the daily note file, replacing the `## Meetings` section if it exists, or creating a new section if it does not. 
# 4. The additional files in the tar file are copied to the vault at `C:\Users\jmutchek\OneDrive - Microsoft\10-self\12-journal\12.10-journal\`
# 5. Validate that the daily note file has been updated with the meetings information and that the additional files have been copied correctly.
# 6. Clean up the temporary folder used for extraction.
# 7. Rename the tar file to `yyyymmdd-meetings-processed.tar` to indicate that it has been processed.

# Other Requirements
# - The script can be run multiple times without issues (existing files and templated sections are not overwritten)

<#
.SYNOPSIS
    Obsidian Daily Note Meeting Augmentation Script
    
.DESCRIPTION
    This script processes Obsidian daily notes by integrating meeting information from TAR files
    generated by Copilot. It can run in manual mode or watch mode.
    
.PARAMETER ManualMode
    Run in manual mode to process existing daily notes without file watching
    
.PARAMETER DateString
    Specific date to process in yyyy-MM-dd format (only used in manual mode)
#>

param(
    [switch]$ManualMode,
    [string]$DateString
)

# Configuration
$Config = @{
    JournalPath = "C:\Users\jmutchek\OneDrive - Microsoft\10-self\12-journal\12.10-journal\journal"
    VaultPath = "C:\Users\jmutchek\OneDrive - Microsoft\10-self\12-journal\12.10-journal"
    DownloadsPath = "C:\Users\jmutchek\Downloads"
    TempPath = Join-Path $env:TEMP "DailyNoteProcessor"
}

# Logging function
function Write-Log {
    param(
        [string]$Message,
        [ValidateSet("Info", "Warning", "Error")]
        [string]$Level = "Info"
    )
    
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logMessage = "[$timestamp] [$Level] $Message"
    
    switch ($Level) {
        "Warning" { Write-Warning $logMessage }
        "Error" { Write-Error $logMessage }
        default { Write-Host $logMessage -ForegroundColor Green }
    }
}

# Convert date formats
function ConvertTo-DateFormats {
    param([DateTime]$Date)
    
    return @{
        DailyNoteFormat = $Date.ToString("yyyy-MM-dd")
        TarFileFormat = $Date.ToString("yyyyMMdd")
        MeetingsFileFormat = $Date.ToString("yyyyMMdd")
    }
}

# Check if TAR file exists for given date
function Test-MeetingsTarFile {
    param([string]$DateString)
    
    $tarFileName = "$DateString-meetings.tar"
    $tarFilePath = Join-Path $Config.DownloadsPath $tarFileName
    
    if (Test-Path $tarFilePath) {
        Write-Log "Found meetings TAR file: $tarFilePath"
        return $tarFilePath
    } else {
        Write-Log "No meetings TAR file found for date $DateString" -Level "Warning"
        return $null
    }
}

# Extract TAR file contents
function Expand-MeetingsTar {
    param(
        [string]$TarFilePath,
        [string]$DestinationPath
    )
    
    try {
        # Ensure destination directory exists
        if (-not (Test-Path $DestinationPath)) {
            New-Item -ItemType Directory -Path $DestinationPath -Force | Out-Null
        }
        
        Write-Log "Extracting TAR file to: $DestinationPath"
        
        # Use tar command to extract
        $result = & tar -xf $TarFilePath -C $DestinationPath 2>&1
        
        if ($LASTEXITCODE -eq 0) {
            Write-Log "TAR extraction completed successfully"
            return $true
        } else {
            Write-Log "TAR extraction failed: $result" -Level "Error"
            return $false
        }
    }
    catch {
        Write-Log "Error extracting TAR file: $($_.Exception.Message)" -Level "Error"
        return $false
    }
}

# Process daily note file
function Update-DailyNote {
    param(
        [string]$DailyNotePath,
        [string]$MeetingsContent
    )
    
    try {
        if (-not (Test-Path $DailyNotePath)) {
            Write-Log "Daily note file not found: $DailyNotePath" -Level "Error"
            return $false
        }
        
        # Read existing content
        $content = Get-Content $DailyNotePath -Raw -ErrorAction Stop
        
        # Check if ## Meetings section exists and replace it
        $meetingsPattern = '(?ms)^## Meetings\s*\n.*?(?=^##|\z)'
        $newMeetingsSection = "## Meetings`n`n$MeetingsContent"
        
        if ($content -match $meetingsPattern) {
            Write-Log "Replacing existing ## Meetings section"
            $updatedContent = $content -replace $meetingsPattern, $newMeetingsSection
        } else {
            Write-Log "Adding new ## Meetings section"
            # Remove any trailing whitespace and add the new section
            $updatedContent = $content.TrimEnd() + "`n`n$newMeetingsSection"
        }
        
        # Write updated content back to file
        Set-Content -Path $DailyNotePath -Value $updatedContent -Encoding UTF8
        Write-Log "Daily note updated successfully: $DailyNotePath"
        return $true
    }
    catch {
        Write-Log "Error updating daily note: $($_.Exception.Message)" -Level "Error"
        return $false
    }
}

# Copy additional files to vault root
function Copy-AdditionalFiles {
    param(
        [string]$SourcePath,
        [string]$MeetingsFileName
    )
    
    try {
        $sourceFiles = Get-ChildItem -Path $SourcePath -File | Where-Object { $_.Name -ne $MeetingsFileName }
        
        if ($sourceFiles.Count -eq 0) {
            Write-Log "No additional files to copy"
            return $true
        }
        
        foreach ($file in $sourceFiles) {
            $destinationPath = Join-Path $Config.VaultPath $file.Name
            
            # Don't overwrite existing files
            if (Test-Path $destinationPath) {
                Write-Log "File already exists, skipping: $($file.Name)" -Level "Warning"
                continue
            }
            
            Copy-Item -Path $file.FullName -Destination $destinationPath
            Write-Log "Copied file: $($file.Name) to vault root"
        }
        
        return $true
    }
    catch {
        Write-Log "Error copying additional files: $($_.Exception.Message)" -Level "Error"
        return $false
    }
}

# Validate processing results
function Test-ProcessingResults {
    param(
        [string]$DailyNotePath,
        [string]$TempPath
    )
    
    $validationPassed = $true
    
    # Check if daily note was updated
    if (Test-Path $DailyNotePath) {
        $content = Get-Content $DailyNotePath -Raw
        if ($content -match '## Meetings') {
            Write-Log "Validation: Daily note contains ## Meetings section"
        } else {
            Write-Log "Validation failed: ## Meetings section not found in daily note" -Level "Error"
            $validationPassed = $false
        }
    } else {
        Write-Log "Validation failed: Daily note file not found" -Level "Error"
        $validationPassed = $false
    }
    
    return $validationPassed
}

# Clean up temporary files
function Remove-TempFiles {
    param([string]$TempPath)
    
    try {
        if (Test-Path $TempPath) {
            Remove-Item -Path $TempPath -Recurse -Force
            Write-Log "Temporary files cleaned up"
        }
    }
    catch {
        Write-Log "Warning: Could not clean up temporary files: $($_.Exception.Message)" -Level "Warning"
    }
}

# Mark TAR file as processed
function Set-TarFileProcessed {
    param([string]$TarFilePath)
    
    try {
        $directory = Split-Path $TarFilePath
        $fileName = [System.IO.Path]::GetFileNameWithoutExtension($TarFilePath)
        $processedFileName = "$fileName-processed.tar"
        $processedPath = Join-Path $directory $processedFileName
        
        # Don't rename if already processed
        if (Test-Path $processedPath) {
            Write-Log "Processed file already exists, removing original TAR file"
            Remove-Item $TarFilePath -Force
        } else {
            Rename-Item -Path $TarFilePath -NewName $processedFileName
            Write-Log "TAR file marked as processed: $processedFileName"
        }
    }
    catch {
        Write-Log "Warning: Could not rename TAR file: $($_.Exception.Message)" -Level "Warning"
    }
}

# Main processing function
function Invoke-DailyNoteProcessing {
    param([DateTime]$Date)
    
    Write-Log "Starting daily note processing for date: $($Date.ToString('yyyy-MM-dd'))"
    
    $dateFormats = ConvertTo-DateFormats -Date $Date
    
    # Construct nested path: journal/yyyy/mm/yyyy-mm-dd.md
    $yearFolder = $Date.ToString("yyyy")
    $monthFolder = $Date.ToString("MM")
    $dailyNotePath = Join-Path $Config.JournalPath $yearFolder $monthFolder "$($dateFormats.DailyNoteFormat).md"
    
    Write-Log "Looking for daily note at: $dailyNotePath"
    
    # Check if daily note exists
    if (-not (Test-Path $dailyNotePath)) {
        Write-Log "Daily note file not found: $dailyNotePath" -Level "Warning"
        return $false
    }
    
    # Check for meetings TAR file
    $tarFilePath = Test-MeetingsTarFile -DateString $dateFormats.TarFileFormat
    if (-not $tarFilePath) {
        return $false
    }
    
    # Create temporary extraction directory
    $tempPath = Join-Path $Config.TempPath $dateFormats.TarFileFormat
    
    try {
        # Extract TAR file
        if (-not (Expand-MeetingsTar -TarFilePath $tarFilePath -DestinationPath $tempPath)) {
            return $false
        }
        
        # Find meetings markdown file
        $meetingsFileName = "$($dateFormats.MeetingsFileFormat)_meetings.md"
        $meetingsFilePath = Join-Path $tempPath $meetingsFileName
        
        if (-not (Test-Path $meetingsFilePath)) {
            Write-Log "Meetings file not found in TAR: $meetingsFileName" -Level "Error"
            return $false
        }
        
        # Read meetings content
        $meetingsContent = Get-Content $meetingsFilePath -Raw
        
        # Update daily note
        if (-not (Update-DailyNote -DailyNotePath $dailyNotePath -MeetingsContent $meetingsContent)) {
            return $false
        }
        
        # Copy additional files
        if (-not (Copy-AdditionalFiles -SourcePath $tempPath -MeetingsFileName $meetingsFileName)) {
            return $false
        }
        
        # Validate results
        if (-not (Test-ProcessingResults -DailyNotePath $dailyNotePath -TempPath $tempPath)) {
            return $false
        }
        
        # Mark TAR as processed
        Set-TarFileProcessed -TarFilePath $tarFilePath
        
        Write-Log "Daily note processing completed successfully"
        return $true
    }
    finally {
        # Always clean up temp files
        Remove-TempFiles -TempPath $tempPath
    }
}

# Manual mode execution
if ($ManualMode) {
    Write-Log "Running in manual mode"
    
    if ($DateString) {
        try {
            $targetDate = [DateTime]::ParseExact($DateString, "yyyy-MM-dd", $null)
            Invoke-DailyNoteProcessing -Date $targetDate
        }
        catch {
            Write-Log "Invalid date format. Please use yyyy-MM-dd format." -Level "Error"
        }
    } else {
        # Process today's date
        $today = Get-Date
        Invoke-DailyNoteProcessing -Date $today
    }
} else {
    Write-Log "File watching mode not yet implemented. Use -ManualMode to test processing."
}